site_name: MIMOSA documentation

nav:
  - Home: index.md
  - Model documentation:
      - components/index.md
      - Economics: components/economics.md
      - Welfare: components/welfare.md
      - Emissions and temperature: components/emissions.md
      - Mitigation: components/mitigation.md
      - Sea-level rise: components/sealevelrise.md
      - Damages: components/damages.md
      - Effort-sharing: components/effortsharing.md
      - Emission trading: components/emissiontrading.md
      - Financial transfers: components/financialtransfers.md
      - Region definitions: components/regions.md
  - Parameter reference: parameters.md
  - Installing MIMOSA: installation.md
  - Running MIMOSA: run.md
  - MIMOSA Dashboard: "https://dashboard-mimosa.onrender.com/"
  - Extending MIMOSA:
      - extending/index.md
      - New components: extending/components.md
      - Variables and constraints: extending/variables_constraints.md
      - Parameters: extending/parameters.md
      - Units: extending/units.md
  - Model code: "https://github.com/UtrechtUniversity/mimosa"

repo_url: https://github.com/UtrechtUniversity/mimosa

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: assets/logos/favicon.svg
  logo: assets/logos/circle_logo.svg
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top
    # - navigation.expand
    - navigation.indexes
    - navigation.footer

watch:
  - mimosa

hooks:
  - docs/scripts/mkdocs_hooks.py

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
          paths: [src]
  - search
  - table-reader
  - macros:
      include_dir: tests
      module_name: docs/scripts/mkdocs_macros
  - open-in-new-tab
  - plotly:
      template_default: assets/plots/template.json
      template_slate: assets/plots/template_slate.json
  - glightbox
  - bibtex:
      bib_file: docs/assets/references.bib

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css
