name: CI

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install mimosa
        run: |
          pip install .

      - name: Dependency check
        run: |
          pip check

      # Optional: run tests
      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -m "not ipopt"
        continue-on-error: false
