name: Optimisation test with IPOPT

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]
    branches: [master]

jobs:
  test_optimisation:
    if: |
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      contains(github.event.head_commit.message, 'Merge pull request'))
    name: Test with IPOPT on Python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: test-env
          environment-file: tests/environment.yml

      - name: Install mimosa
        shell: bash -l {0}
        run: |
          pip install .

      - name: Dependency check
        shell: bash -l {0}
        run: |
          pip check

      - name: Run full tests (with ipopt)
        shell: bash -l {0}
        run: |
          pytest
